# Generated by Django 4.1.2 on 2022-11-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrowserGame_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='food',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='premium_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='stone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
